import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header/Header'
import Content from '../components/Content/Content'
// import Providers from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <div id="toast-root" className="fixed right-2/4 transform translate-x-2/4 flex flex-col z-30 w-64 space-y-2" />
      <div id="modal-root" className="fixed z-30" />
        <Header />
        <div className="max-w-3xl mx-auto relative">
          {children}
          <Content />
        </div>
    </body>
    </html>
  )
}
